# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='可用库存')),
                ('locked_quantity', models.IntegerField(default=0, verbose_name='锁定库存')),
                ('warning_threshold', models.IntegerField(default=10, verbose_name='预警阈值')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='最后盘点时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '库存',
                'verbose_name_plural': '库存',
                'db_table': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('quantity', models.IntegerField(verbose_name='变动数量')),
                ('before_qty', models.IntegerField(verbose_name='变动前数量')),
                ('after_qty', models.IntegerField(verbose_name='变动后数量')),
                ('biz_type', models.CharField(blank=True, max_length=50, verbose_name='业务类型')),
                ('biz_no', models.CharField(blank=True, max_length=50, verbose_name='业务单号')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '库存流水',
                'verbose_name_plural': '库存流水',
                'db_table': 'inventory_logs',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('code', models.CharField(max_length=50, verbose_name='仓库编码')),
                ('type', models.CharField(default='self', max_length=20, verbose_name='类型')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省/州')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='详细地址')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'db_table': 'warehouses',
            },
        ),
    ]
