# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsku', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='仓库'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsku', verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='仓库'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('warehouse', 'sku')},
        ),
    ]
