# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='公司编码')),
                ('name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='英文名称')),
                ('company_type', models.CharField(default='express', max_length=20, verbose_name='类型')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('tracking_url', models.URLField(blank=True, verbose_name='查询网址')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('supported_countries', models.JSONField(blank=True, default=list, verbose_name='支持国家')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物流公司',
                'verbose_name_plural': '物流公司',
                'db_table': 'logistics_companies',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='渠道名称')),
                ('code', models.CharField(max_length=50, verbose_name='渠道编码')),
                ('method_type', models.CharField(choices=[('standard', '标准快递'), ('express', '特快专递'), ('economy', '经济快递'), ('sea', '海运'), ('air', '空运')], max_length=20, verbose_name='运输方式')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.logisticscompany', verbose_name='物流公司')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '物流渠道',
                'verbose_name_plural': '物流渠道',
                'db_table': 'shipping_methods',
            },
        ),
    ]
