# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='平台名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='平台编码')),
                ('icon', models.URLField(blank=True, verbose_name='图标')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('api_base_url', models.URLField(blank=True, verbose_name='API地址')),
                ('auth_type', models.CharField(default='oauth', max_length=20, verbose_name='认证类型')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电商平台',
                'verbose_name_plural': '电商平台',
                'db_table': 'platforms',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('shop_code', models.CharField(blank=True, max_length=50, verbose_name='店铺编码')),
                ('platform_shop_id', models.CharField(blank=True, max_length=100, verbose_name='平台店铺ID')),
                ('auth_token', models.TextField(blank=True, verbose_name='授权令牌')),
                ('refresh_token', models.TextField(blank=True, verbose_name='刷新令牌')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='令牌过期时间')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('sync_status', models.SmallIntegerField(default=0, verbose_name='同步状态')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'db_table': 'shops',
            },
        ),
    ]
