# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='系统订单号')),
                ('platform_order_no', models.CharField(max_length=100, verbose_name='平台订单号')),
                ('platform_id', models.IntegerField(verbose_name='平台ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('paid', '已付款'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('order_status', models.CharField(blank=True, max_length=50, verbose_name='平台原始状态')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='币种')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='订单总金额')),
                ('product_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='商品金额')),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='运费')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='优惠金额')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='税费')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='实付金额')),
                ('buyer_id', models.CharField(blank=True, max_length=100, verbose_name='买家ID')),
                ('buyer_name', models.CharField(blank=True, max_length=100, verbose_name='买家名称')),
                ('buyer_email', models.EmailField(blank=True, max_length=254, verbose_name='买家邮箱')),
                ('buyer_phone', models.CharField(blank=True, max_length=50, verbose_name='买家电话')),
                ('receiver_name', models.CharField(blank=True, max_length=100, verbose_name='收件人')),
                ('receiver_phone', models.CharField(blank=True, max_length=50, verbose_name='收件电话')),
                ('receiver_country', models.CharField(blank=True, max_length=50, verbose_name='国家')),
                ('receiver_province', models.CharField(blank=True, max_length=100, verbose_name='省/州')),
                ('receiver_city', models.CharField(blank=True, max_length=100, verbose_name='城市')),
                ('receiver_district', models.CharField(blank=True, max_length=100, verbose_name='区/县')),
                ('receiver_address', models.CharField(blank=True, max_length=500, verbose_name='详细地址')),
                ('receiver_zipcode', models.CharField(blank=True, max_length=20, verbose_name='邮编')),
                ('remark', models.TextField(blank=True, verbose_name='订单备注')),
                ('buyer_message', models.TextField(blank=True, verbose_name='买家留言')),
                ('seller_memo', models.TextField(blank=True, verbose_name='卖家备注')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=100, verbose_name='物流单号')),
                ('carrier_id', models.IntegerField(blank=True, null=True, verbose_name='物流商ID')),
                ('carrier_name', models.CharField(blank=True, max_length=50, verbose_name='物流商名称')),
                ('carrier_code', models.CharField(blank=True, max_length=50, verbose_name='物流商编码')),
                ('shipping_method', models.CharField(blank=True, max_length=50, verbose_name='运输方式')),
                ('status', models.CharField(choices=[('pending', '待发货'), ('shipped', '已发货'), ('delivered', '已签收'), ('returned', '已退回')], default='pending', max_length=20, verbose_name='状态')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='包裹重量')),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际运费')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='预计送达')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='发货时间')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='送达时间')),
                ('tracking_data', models.JSONField(blank=True, default=list, verbose_name='物流轨迹')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order', verbose_name='订单')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipments', to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '订单物流',
                'verbose_name_plural': '订单物流',
                'db_table': 'order_shipments',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_product_id', models.CharField(blank=True, max_length=100, verbose_name='平台商品ID')),
                ('platform_sku_id', models.CharField(blank=True, max_length=100, verbose_name='平台SKU ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('sku_name', models.CharField(blank=True, max_length=255, verbose_name='SKU规格')),
                ('image', models.URLField(blank=True, verbose_name='商品图片')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总价')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='成本价')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='重量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
                'db_table': 'order_items',
            },
        ),
    ]
