# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(max_length=50, unique=True, verbose_name='交易单号')),
                ('biz_type', models.CharField(choices=[('order', '订单'), ('purchase', '采购'), ('refund', '退款'), ('other', '其他')], max_length=20, verbose_name='业务类型')),
                ('biz_id', models.BigIntegerField(blank=True, null=True, verbose_name='业务单ID')),
                ('biz_no', models.CharField(blank=True, max_length=50, verbose_name='业务单号')),
                ('type', models.CharField(max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='金额')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='币种')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '交易流水',
                'verbose_name_plural': '交易流水',
                'db_table': 'transactions',
            },
        ),
    ]
