# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=50, unique=True, verbose_name='采购单号')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending', '待确认'), ('confirmed', '已确认'), ('received', '已收货'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='总数量')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='收货时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '采购订单',
                'verbose_name_plural': '采购订单',
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='供应商名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='供应商编码')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='联系邮箱')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('website', models.URLField(blank=True, verbose_name='网站')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='采购数量')),
                ('received_quantity', models.IntegerField(default=0, verbose_name='已收货数量')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单价')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总价')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorder', verbose_name='采购单')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsku', verbose_name='SKU')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '采购明细',
                'verbose_name_plural': '采购明细',
                'db_table': 'purchase_order_items',
            },
        ),
    ]
