# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='租户名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='租户编码')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('plan', models.CharField(default='basic', max_length=20, verbose_name='套餐')),
                ('expired_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('contact_name', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('contact_email', models.EmailField(blank=True, max_length=100, verbose_name='联系邮箱')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='租户配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'tenants',
            },
        ),
    ]
