# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spu_code', models.CharField(max_length=50, verbose_name='SPU编码')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='英文名称')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('description_en', models.TextField(blank=True, verbose_name='英文描述')),
                ('brand', models.CharField(blank=True, max_length=50, verbose_name='品牌')),
                ('main_image', models.URLField(blank=True, verbose_name='主图')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片列表')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='重量(kg)')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='长(cm)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='宽(cm)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='高(cm)')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='材质')),
                ('origin', models.CharField(blank=True, max_length=50, verbose_name='产地')),
                ('hs_code', models.CharField(blank=True, max_length=20, verbose_name='海关编码')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('source_type', models.CharField(blank=True, max_length=20, verbose_name='来源')),
                ('source_url', models.URLField(blank=True, verbose_name='来源URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=50, verbose_name='SKU编码')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='条形码')),
                ('spec_info', models.JSONField(default=dict, verbose_name='规格信息')),
                ('spec_image', models.URLField(blank=True, verbose_name='规格图片')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='采购价')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='成本价')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='销售价')),
                ('market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='市场价')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='重量(kg)')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product', verbose_name='商品')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU',
                'db_table': 'product_skus',
            },
        ),
        migrations.CreateModel(
            name='ProductPlatformMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_product_id', models.CharField(blank=True, max_length=100, verbose_name='平台商品ID')),
                ('platform_sku_id', models.CharField(blank=True, max_length=100, verbose_name='平台SKU ID')),
                ('platform_listing_id', models.CharField(blank=True, max_length=100, verbose_name='平台刊登ID')),
                ('listing_status', models.SmallIntegerField(default=0, verbose_name='刊登状态')),
                ('listing_data', models.JSONField(blank=True, default=dict, verbose_name='刊登数据')),
                ('last_listed_at', models.DateTimeField(blank=True, null=True, verbose_name='最后刊登时间')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='商品')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.shop', verbose_name='店铺')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsku', verbose_name='SKU')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '平台映射',
                'verbose_name_plural': '平台映射',
                'db_table': 'product_platform_mappings',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='分类编码')),
                ('level', models.SmallIntegerField(default=1, verbose_name='层级')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory', verbose_name='父分类')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'db_table': 'product_categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productcategory', verbose_name='分类'),
        ),
    ]
