# Generated by Django 4.2.29 on 2026-04-01 02:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='租户'),
        ),
        migrations.AlterUniqueTogether(
            name='productsku',
            unique_together={('tenant', 'sku_code')},
        ),
        migrations.AlterUniqueTogether(
            name='productplatformmapping',
            unique_together={('sku', 'shop')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'spu_code')},
        ),
    ]
